version: 2
job_common: &job_common
  docker:
    - image: circleci/node:8.11.3
  working_directory: ~/ElectusProtocol
step_save_cache: &step_save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules
step_restore_cache: &step_restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      sudo npm install -g truffle
      npm install

jobs:
  build:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Build code for Electus Protocol"
          command: truffle compile
      - <<: *step_save_cache
  unit-test:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Run Tests for Electus Protocol"
          command: npm run test
      - <<: *step_save_cache
      # Save test results
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml

workflows:
  version: 2
  commit:
    jobs:
      - build
      - unit-test
